# Generated by Django 6.0.3 on 2026-03-15 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=200)),
                ('completed', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=100)),
            ],
        ),
    ]
